#!/usr/bin/env python3
"""Build the exploration tracker from upstream catalog data plus local status.

Inputs (upstream, read-only):  overview.tex, lean/docs/NNN.md, reasoning_traces/
Input (ours, hand-edited):     exploration/status.csv
Outputs (generated):           exploration/catalog.csv, exploration/TRACKER.md

Run from anywhere:  python3 exploration/build_tracker.py
"""

import csv
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXP = ROOT / "exploration"
STATUS_FILE = EXP / "status.csv"
STATUSES = ["unread", "skimmed", "reading", "deep-dive", "checked", "parked"]

# Families with an abridged reasoning summary, per the upstream README.
REASONING_TRACES = {
    "007": "ordinary-two-point-correlations.pdf",
    "017": "irrationality-exponent-of-pi.pdf",
    "087": "symmetric-and-general-mahler-conjectures.pdf",
    "102": "basic-semidefinite-threshold-np-hardness.pdf",
    "159": "quasipolynomial-arithmetic-progressions.pdf",
    "197": "kaplansky-direct-finiteness-characteristic-two.pdf",
    "221": "mezard-parisi-formula.pdf",
    "271": "spontaneous-magnetization-quantum-heisenberg-ferromagnet.pdf",
    "287": "free-group-factor-isomorphism.pdf",
    "362": "relativistic-vlasov-maxwell.pdf",
}


def read_braced(s, i):
    """Return (content, next_index) for the {...} group starting at s[i]."""
    assert s[i] == "{", s[i : i + 20]
    depth, j = 0, i
    while True:
        c = s[j]
        if c == "\\":
            j += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return s[i + 1 : j], j + 1
        j += 1


def tex_to_text(t):
    t = re.sub(r"\\href\{[^}]*\}\{([^}]*)\}", r"\1", t)
    t = re.sub(r"\\(textit|textbf|emph|mathrm|operatorname)\{([^}]*)\}", r"\2", t)
    t = t.replace("---", "—").replace("--", "–").replace("~", " ")
    t = re.sub(r"\\['\"`^]\{?(\w)\}?", r"\1", t)
    return re.sub(r"\s+", " ", t).strip()


def parse_overview():
    s = (ROOT / "overview.tex").read_text()
    body = s[s.index("\\begin{document}") :]
    families, discipline = [], None
    for m in re.finditer(r"\\(cataloguesection|resultentry)(?=\{)", body):
        i = m.end()
        if m.group(1) == "cataloguesection":
            discipline, _ = read_braced(body, i)
            continue
        num, i = read_braced(body, i)
        title, i = read_braced(body, i)
        desc, i = read_braced(body, i)
        links, i = read_braced(body, i)
        papers = re.findall(r"\\href\{https://github\.com/openai/math/blob/main/([^}]*)\}", links)
        families.append(
            {
                "family": num,
                "discipline": discipline,
                "title": tex_to_text(title),
                "summary": tex_to_text(desc),
                "papers": papers,
            }
        )
    return families


def load_status():
    if not STATUS_FILE.exists():
        return {}
    with STATUS_FILE.open() as f:
        return {r["family"].zfill(3): r for r in csv.DictReader(f)}


def main():
    families = parse_overview()
    lean = {p.stem for p in (ROOT / "lean/docs").glob("[0-9][0-9][0-9].md")}
    status = load_status()

    for fam in families:
        n = fam["family"]
        st = status.get(n, {})
        fam["lean"] = n in lean
        fam["trace"] = REASONING_TRACES.get(n, "")
        fam["status"] = st.get("status") or "unread"
        fam["priority"] = st.get("priority", "")
        fam["notes"] = st.get("notes", "")
        if fam["status"] not in STATUSES:
            raise SystemExit(f"family {n}: unknown status {fam['status']!r}; use one of {STATUSES}")

    with (EXP / "catalog.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["family", "discipline", "title", "manuscripts", "lean", "reasoning_trace", "first_paper"])
        for fam in families:
            w.writerow(
                [fam["family"], fam["discipline"], fam["title"], len(fam["papers"]),
                 "yes" if fam["lean"] else "", fam["trace"], fam["papers"][0] if fam["papers"] else ""]
            )

    by_disc = defaultdict(list)
    for fam in families:
        by_disc[fam["discipline"]].append(fam)
    status_counts = Counter(f["status"] for f in families)

    out = [
        "# Exploration tracker",
        "",
        "Generated by `exploration/build_tracker.py` — edit `exploration/status.csv`, not this file.",
        "",
        f"**{len(families)} families · {sum(len(f['papers']) for f in families)} manuscript links · "
        f"{sum(f['lean'] for f in families)} with Lean docs · {len(REASONING_TRACES)} with reasoning traces**",
        "",
        "Progress: " + " · ".join(f"{s}: {status_counts.get(s, 0)}" for s in STATUSES),
        "",
        "Legend: **L** = Lean formalization doc in `lean/docs/`, **R** = abridged reasoning trace in `reasoning_traces/`.",
        "",
        "## By discipline",
        "",
        "| Discipline | Families | Lean | Explored |",
        "| --- | ---: | ---: | ---: |",
    ]
    for disc, fams in by_disc.items():
        explored = sum(f["status"] != "unread" for f in fams)
        anchor = re.sub(r"[^a-z0-9 -]", "", disc.lower()).replace(" ", "-")
        out.append(f"| [{disc}](#{anchor}) | {len(fams)} | {sum(f['lean'] for f in fams)} | {explored} |")

    for disc, fams in by_disc.items():
        out += ["", f"## {disc}", "", "| # | Result | Papers | L | R | Status | Pri | Notes |", "| --- | --- | ---: | --- | --- | --- | --- | --- |"]
        for fam in fams:
            n = fam["family"]
            title = f"[{fam['title']}](../{fam['papers'][0]})" if fam["papers"] else fam["title"]
            lean_cell = f"[L](../lean/docs/{n}.md)" if fam["lean"] else ""
            trace_cell = f"[R](../reasoning_traces/{fam['trace']})" if fam["trace"] else ""
            note_file = EXP / "notes" / f"{n}.md"
            notes = fam["notes"].replace("|", "\\|")
            if note_file.exists():
                notes = (f"[notes](notes/{n}.md) " + notes).strip()
            out.append(
                f"| {n} | {title.replace('|', '\\|')} | {len(fam['papers'])} | {lean_cell} | {trace_cell} | "
                f"{fam['status']} | {fam['priority']} | {notes} |"
            )

    (EXP / "TRACKER.md").write_text("\n".join(out) + "\n")
    print(f"{len(families)} families, {len(lean)} lean docs, {len(status)} status rows -> TRACKER.md, catalog.csv")


if __name__ == "__main__":
    main()
